/** Mots-clés par catégorie — matching local + enrichissement recherche web */

export const categoryKeywords: Record<string, string[]> = {
  Alimentation: [
    "carrefour",
    "leclerc",
    "auchan",
    "lidl",
    "intermarche",
    "monoprix",
    "franprix",
    "super u",
    "superu",
    "restaurant",
    "mcdo",
    "mcdonald",
    "uber eats",
    "ubereats",
    "deliveroo",
    "just eat",
    "boulangerie",
    "boulanger",
    "picard",
    "match",
    "casino",
    "supermarche",
    "epicerie",
    "biocoop",
    "naturalia",
    "flunch",
    "sushi",
    "pizza",
    "kebab",
    "starbucks",
    "paul ",
    "kfc",
    "burger",
    "subway",
  ],
  Transport: [
    "sncf",
    "ratp",
    "uber",
    "bolt",
    "total",
    "shell",
    "bp ",
    "esso",
    "parking",
    "peage",
    "autoroute",
    "velib",
    "lime",
    "taxi",
    "blablacar",
    "ouigo",
    "e.leclerc carbur",
    "carburant",
    "indigo park",
    "vinci",
  ],
  Logement: [
    "loyer",
    "edf",
    "engie",
    "electricite",
    "gaz",
    "veolia",
    "eau ",
    "assurance habitation",
    "syndic",
    "foncia",
    "citya",
  ],
  Loisirs: [
    "netflix",
    "spotify",
    "cinema",
    "ugc",
    "mk2",
    "steam",
    "playstation",
    "xbox",
    "nintendo",
    "disney",
    "canal+",
    "canal plus",
    "salle de sport",
    "basic fit",
    "fitness park",
    "keepcool",
    "decathlon",
  ],
  Santé: [
    "pharmacie",
    "doctolib",
    "mutuelle",
    "hopital",
    "medecin",
    "dentiste",
    "optique",
    "laboratoire",
    "kine",
  ],
  Shopping: [
    "amazon",
    "zara",
    "hm ",
    "h&m",
    "decathlon",
    "fnac",
    "darty",
    "ikea",
    "shein",
    "cdiscount",
    "vinted",
    "leboncoin",
    "action ",
    "normal ",
    "primark",
    "cultura",
    "boulanger ",
    "apple store",
    "sephora",
  ],
  Abonnements: [
    "abonnement",
    "forfait",
    "orange",
    "sfr",
    "free mobile",
    "free.fr",
    "bouygues",
    "microsoft",
    "google",
    "apple",
    "adobe",
    "dropbox",
    "ovh",
    "cloudflare",
    "github",
    "notion",
  ],
  Salaire: ["salaire", "paie", "remuneration", "bulletin de paie", "employeur"],
  "Autres revenus": ["remboursement", "prime", "dividende", "caf", "cpam"],
};
